### ISSUE TITLE
Multiple Choices

### ISSUE THREAD

**Issue by PaulD11** [inmagik/ionic-modal-select#48] opened 2016-05-05 10:03 UTC
Hi,

this really a great plugin, but i can't figure out how to choose more than one options without closing the modal.

**Comment by bianchimro** [comment] 2016-05-05 10:49
hi @PaulD11 , thanks for your appreciation.
I don't understand well your use case, can you make a codepen or something similar to illustrate it?
regards

Mauro

**Comment by PaulD11** [comment] 2016-05-05 12:22
Something like that: 
![image](https://cloud.githubusercontent.com/assets/14149270/15043364/c0dfd522-12cc-11e6-852f-b5ef3f8b5256.png)
Select more than one item without closing the modal

**Comment by bianchimro** [comment] 2016-05-05 12:48
Ok, I understand now,
this is about #1, which is working now in master branch but not yet documented.

I'm going to close that issue and document it ASAP, in the meantime you could just try an
d add the `multiple` attribute to your tag and see if the result works for you

**Comment by PaulD11** [comment] 2016-05-05 12:58
Perfect, thanks a lot!

**Comment by aysyal31** [comment] 2016-05-24 13:25
The search functionality doesn't work in the new mainline. Is it ? can you please check.

**Comment by PaulD11** [comment] 2016-05-24 13:36
Yes that's correct. In the single choice view it's working fine but if you add a multiple it isn't working

**Comment by ramosinfo** [comment] 2016-08-25 19:31
You can do it?

**Comment by PaulD11** [comment] 2016-08-26 14:42
Yes I did it with ionic-Filter-bar

**Comment by ramosinfo** [comment] 2016-08-26 15:02
Can you send an example?

**Comment by bianchimro** [comment] 2016-09-14 21:01
closing, duplicate of #1

**Closed by bianchimro** 2016-09-14 21:01 UTC
Labels: needs_example
